#ifndef TRIANGLE_GLOBAL_H
#define TRIANGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRIANGLE_LIBRARY)
#  define TRIANGLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRIANGLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRIANGLE_GLOBAL_H
